### ISSUE TITLE
num_typos in openapi.yml should be oneOf

### ISSUE THREAD

**Issue by softwarespot** [typesense/typesense-api-spec#33]
## Description

Thanks for an amazing and well structured project. I feel bad mentioning this, but I have found an issue and would like to understand if this was intentional or a bug? :thinking: 

https://github.com/typesense/typesense-api-spec/blob/master/openapi.yml#L1732 as you know, is used to build the [Go client](https://github.com/typesense/typesense-go/blob/master/typesense/api/generator/main.go#L28) for Typesense, but unfortunately the schema doesn't quite match the changes which were introduced in 0.21.0. I am referring particularly to the search params field `num_typos`, in which previously it used to be an `integer`, but now can be either `integer` or `string of integers`.

This is at least a problem, when decoding i.e. unmarshling search params as JSON to the search params struct, as it returns an error, when a `string` is used. However, the documentation documents this is valid.

My questions are:

* Is there a reason for `num_typos` not being updated in `openapi.yml`? Breaking API change?
* A new field was not created instead e.g. `num_typos_multi` (sorry for the bad name)

Again, your answers are much appreciated.

## Steps to reproduce
N/A

## Expected Behavior
N/A

## Actual Behavior
N/A

## Metadata
**Typesense Version**: 0.24.0

**OS**: Ubuntu 22.10

**Comment by kishorenc** [comment]
Yes, `num_typos` should be a string because you can pass a comma separated list of true/false values that matches the number of fields in `quey_by`. Same behavior already applies to other options like `prefix`. 

The change has been missed: we should make it a string. The API can take either a single value `2` or comma separated values. If a single value is given but multiple fields are queried, we will just use that value for all fields. This maintains backward compatibility at the HTTP API level.

**Comment by softwarespot** [comment]
Thanks for responding quickly, very much appreciated.

So the API spec would change this from *int to *string, if I think from the Go perspective? Is this something the team would be able to fix?

**Comment by kishorenc** [comment]
Yes, I will be fixing this over the next few days.

**Comment by softwarespot** [comment]
Excellent.

**Comment by kishorenc** [comment]
@softwarespot 

I've updated the Go client with the latest changes -- can you please give it a try? I have not published a release yet, so you have try from the HEAD.

**Comment by softwarespot** [comment]
Thanks. The changes are looking pretty much what I did by changing to `*string`. I can give it a try and will let you know ASAP. 

Again, very much appreciated for your time and effort

**Comment by softwarespot** [comment]
Should these places also be updated to `*string`?

* https://github.com/typesense/typesense-go/blob/master/typesense/api/types_gen.go#L244
* https://github.com/typesense/typesense-go/blob/master/typesense/api/types_gen.go#L364

**Comment by kishorenc** [comment]
Fixed again

**Comment by softwarespot** [comment]
Excellent. I will look at this today. Thanks
