### ISSUE TITLE
Update for v0.25

### ISSUE THREAD

**Issue by tadejsv** [typesense/typesense-api-spec#42]
I notice that this API spec is stil at version 0.24, and does not have some updates for version 0.25 (like `limit` and `offset`) parameters.

I would really appreciate if it could be updated - I am trying to build a custom client based on this API.

Also, I notice that Go client is built by codegeneration from this API spec. I think best practice would be to source the API spec from this repo, which would be included as a submodule in the Go client repo, instead of copying the spec.

cc @kishorenc

**Comment by kishorenc** [comment]
This has been fixed.
