### ISSUE TITLE
HTTP status code MUST be enclosed in quotation marks

### ISSUE THREAD

**Issue by kianmeng** [typesense/typesense-api-spec#50]
## Description

The response HTTP status code, as shown below in line 62, in the `openapi.yml` file should be quoted:

```yaml
    61       responses:
    62         200:
    63           description: List of all collections
    64           content: 
    65             application/json:
    66               schema:
    67                 type: array
    68                 x-go-type: "[]*CollectionResponse"
    69                 items:
    70                   $ref: "#/components/schemas/CollectionResponse"
```
In some OpenAPI generators, some generators treat numbers in keys as integers instead of strings by default, which led to error.

As per OpenAPI spec (emphasis added), https://spec.openapis.org/oas/v3.0.3#patterned-fields-0:

> Any [HTTP status code](https://spec.openapis.org/oas/v3.0.3#http-status-codes) can be used as the property name, but only one property per code, to describe the expected response for that HTTP status code. A [Reference Object](https://spec.openapis.org/oas/v3.0.3#reference-object) can link to a response that is defined in the [OpenAPI Object’s components/responses](https://spec.openapis.org/oas/v3.0.3#componentsResponses) section. **This field MUST be enclosed in quotation marks (for example, “200”) for compatibility between JSON and YAML.** To define a range of response codes, this field MAY contain the uppercase wildcard character X. For example, 2XX represents all response codes between [200-299]. Only the following range definitions are allowed: 1XX, 2XX, 3XX, 4XX, and 5XX. If a response is defined using an explicit code, the explicit code definition takes precedence over the range definition for that code.

## Expected Behavior

```diff
    61       responses:
+   62         '200':
```

## Metadata

**Typesense Version**:

**OS**:

**Comment by kianmeng** [comment]
@kishorenc From the recent changes to https://github.com/typesense/typesense-api-spec/blob/master/openapi.yml, we have to update all status code, for example, from integer `200` to string `'200'`?

**Comment by kishorenc** [comment]
Makes sense, yeah we should stick to the spec.
