### ISSUE TITLE
Update Spec to v26.0

### ISSUE THREAD

**Issue by TroyKomodo** [typesense/typesense-api-spec#54]
## Description

Currently this spec is only for v0.25.0 when the latest release is v26.0

**Comment by TroyKomodo** [comment]
I was looking to update the Rust SDK when I realized the spec crate has an older version.

**Comment by TroyKomodo** [comment]
bump @kishorenc

**Comment by kishorenc** [comment]
The spec has already been kept up to date with changes in v26. I have now updated the version property to reflect that as well.
